[gateway]
url = "https://agents.actionllama.org"

[model]
provider = "anthropic"
model = "claude-sonnet-4-20250514"
thinkingLevel = "medium"
authType = "api_key"

[cloud]
provider = "ecs"
awsRegion = "us-east-1"
ecrRepository = "555876763362.dkr.ecr.us-east-1.amazonaws.com/al-repo"
ecsCluster = "al-cluster"
executionRoleArn = "arn:aws:iam::555876763362:role/al-ecs-execution-role"
taskRoleArn = "arn:aws:iam::555876763362:role/al-default-task-role"
subnets = [ "subnet-097aeaae203951749", "subnet-0031866f0ab4be512", "subnet-047022cca144180e8", "subnet-04a854e947e8c2863", "subnet-08cb61d9406cd7973", "subnet-02428c5215fcb1027" ]
securityGroups = [ "sg-046e13bd1a9067ae0" ]

[webhooks.github]
type = "github"
credential = "action-llama"
