models = ["deep"]
credentials = ["github_token", "git_ssh"]
maxWorkQueueSize = 1

[[webhooks]]
source = "github"
events = ["workflow_run"]
actions = ["completed"]
conclusions = ["failure"]
branches = ["main"]

[params]
org = "Action-Llama"
